name: civicsense
description: Raising the Civic Sense 
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_dotenv: ^2.1.0
  googleapis: ^6.0.0
  googleapis_auth: ^1.2.0
  cached_network_image: ^3.1.0
  getwidget: ^2.0.4
  url_launcher: ^6.0.12
  flutter_login: ^2.2.1
  firestore_ui: ^1.21.0
  http: ^0.13.4
  intl: ^0.17.0
  timeago: ^3.1.0
  share: ^2.0.4
  flutter_inappwebview: ^5.3.2
  flutter_tags: "^0.4.9+1"

  google_place:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
