name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_dotenv: ^2.1.0
  googleapis: ^6.0.0
  googleapis_auth: ^1.2.0
  cached_network_image: ^3.1.0
  getwidget: ^2.0.4
  flutter_inappwebview: ^5.3.2

  google_place:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
